#!/bin/sh

uci set network.wan='interface'
uci set network.wan.device='wan'
uci set network.wan.proto='pppoe'
uci set network.wan.username='13971444381'
uci set network.wan.password='888888'
uci set network.wan.ipv6='auto'
uci set network.wan.norelease='1'

uci set network.wan_dev='device'
uci set network.wan_dev.name='wan'
uci set network.wan_dev.macaddr='60:BE:B4:10:AF:F4'

uci commit network
